import type {Metadata} from 'next';
import MusicProvider from '@/src/context/music-context';
import AppProvider from '@/src/context/app-context';
import UserProvider from '@/src/context/user-context';
import './globals.css';
import '../styles/home.css';
import '../styles/custome.css';

export const metadata: Metadata = {
	title: 'Aloi MP3',
	description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<AppProvider>
				<UserProvider>
					<MusicProvider>
						<body>{children}</body>
					</MusicProvider>
				</UserProvider>
			</AppProvider>
		</html>
	);
}
